# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Restore tool
      run: | 
        cd src
        cd WebAPI2Excel
        dotnet tool restore        
    - name: Build
      run: | 
        cd src
        cd WebAPI2Excel
        dotnet r build
    - name: pack
      run: | 
        cd src
        cd WebAPI2Excel
        dotnet r pack


    - name: 'Upload nuget'
      # if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v4
      with:
        name: NugetWebApiExport_${{github.run_number}}
        path: src/WebAPI2Excel/Nuget
        retention-days: 1
  
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal

    - name: push to nuget
      run: |
        dotnet nuget push src/WebAPI2Excel/Nuget/*.symbols.nupkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json
        
    